version: 0.2

phases:
  pre_build:
    commands:
      # install serverless
      - npm install -g serverless
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - npm install
  build:
    commands:
      # transpile typescript
      - echo transpiling typescript
      - npm run build
  post_build:
    commands: serverless deploy
