org: joabsmith
app: scouter
service: scouter

frameworkVersion: "2"

provider:
  name: aws
  stage: dev
  region: us-east-2
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  endpointType: REGIONAL
  ecr:
    images:
      scouterLambdas:
        path: ./

functions:
  PostGetOne:
    image: 
      name: scouterLambdas
      command: 
        - '/Post/GetOne/PostGetOne.handler'
    events:
      - http:
         path: Post
         method: get
  PostAddOne:
    image: 
      name: scouterLambdas
      command: 
        - '/Post/AddOne/PostAddOne.handler'
    events:
      - http:
         path: Post
         method: post
  PostUpdateOne:
    image: 
      name: scouterLambdas
      command: 
        - '/Post/UpdateOne/PostUpdateOne.handler'
    events:
      - http:
         path: Post
         method: put
  PostUpdateOne:
    image: 
      name: scouterLambdas
      command: 
        - '/Post/Delete/PostDeleteOne.handler'
    events:
      - http:
         path: Post
         method: delete
  PostGetAllFollowed:
    image: 
      name: scouterLambdas
      command: 
        - '/Post/GetAllFollowed/PostGetAllFollowed.handler'
    events:
      - http:
         path: Post/follow
         method: get
  PostGetAllPage:
    image: 
      name: scouterLambdas
      command: 
        - '/Post/GetAllPage/PostGetAllPage.handler' 
    events:
      - http:
         path: Post/Page
         method: get



