org: joabsmith
app: scouter
service: scouter

frameworkVersion: "2"

provider:
  name: aws
  stage: dev
  region: us-east-2
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  endpointType: REGIONAL
  ecr:
    images:
      scouterLambdas:
        path: ./
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 'arn:aws:dynamodb:us-east-2:*:*'

functions:
  PostGetOne:
    image: 
      name: scouterLambdas
      command: 
        - '/Post/GetOne/PostGetOne.handler'
    events:
      - http:
         path: Post
         method: get
  PostAddOne:
    image: 
      name: scouterLambdas
      command: 
        - '/Post/AddOne/PostAddOne.handler'
    events:
      - http:
         path: Post
         method: post
  PostUpdateOne:
    image: 
      name: scouterLambdas
      command: 
        - '/Post/UpdateOne/PostUpdateOne.handler'
    events:
      - http:
         path: Post
         method: put
  PostDeleteOne:
    image: 
      name: scouterLambdas
      command: 
        - '/Post/Delete/PostDeleteOne.handler'
    events:
      - http:
         path: Post
         method: delete
  PostGetAllFollowed:
    image: 
      name: scouterLambdas
      command: 
        - '/Post/GetAllFollowed/PostGetAllFollowed.handler'
    events:
      - http:
         path: Post/follow
         method: get
  PostGetAllPage:
    image: 
      name: scouterLambdas
      command: 
        - '/Post/GetAllPage/PostGetAllPage.handler' 
    events:
      - http:
         path: Post/Page
         method: get
  AnimeGetOne:
      image: 
        name: scouterLambdas
        command: 
          - '/Anime/GetOne/AnimeGetOne.handler'
      events:
        - http:
          path: Post
          method: get
  AnimeAddOne:
      image: 
        name: scouterLambdas
        command: 
          - '/Anime/AddOne/AnimeAddOne.handler'
      events:
        - http:
          path: Post
          method: post
  AnimeUpdateOne:
      image: 
        name: scouterLambdas
        command: 
          - '/Anime/UpdateOne/AnimeUpdateOne.handler'
      events:
        - http:
          path: Post
          method: put
  AnimeDeleteOne:
      image: 
        name: scouterLambdas
        command: 
          - '/Anime/DeleteOne/AnimeDeleteOne.handler'
      events:
        - http:
          path: Post
          method: delete
  AnimeGetBySearch:
      image: 
        name: scouterLambdas
        command: 
          - '/Anime/GetBySearch/AnimeGetBySearch.handler'
      events:
        - http:
          path: Post/search
          method: get      
  AnimeGetAll:
      image: 
        name: scouterLambdas
        command: 
          - '/Anime/UpdateOne/AnimeUpdateOne.handler'
      events:
        - http:
          path: Post/Anime
          method: get
  UserGetOne:
      image: 
        name: scouterLambdas
        command: 
          - '/User/GetOne/GetUser.handler'
      events:
        - http:
          path: Post
          method: get 
  UserAddOne:
      image: 
        name: scouterLambdas
        command: 
          - '/User/AddOne/AddUser.handler'
      events:
        - http:
          path: Post
          method: post 
  UserUpdateOne:
      image: 
        name: scouterLambdas
        command: 
          - '/User/UpdateOne/UpdateUser.handler'
      events:
        - http:
          path: Post
          method: put    
  UserDeleteOne:
      image: 
        name: scouterLambdas
        command: 
          - '/User/DeleteOne/DeleteUser.handler'
      events:
        - http:
          path: Post
          method: delete
  UserGetAll:
      image: 
        name: scouterLambdas
        command: 
          - '/User/UpdateOne/GetAllUsers.handler'
      events:
        - http:
          path: Post/User
          method: get