org: joabsmith
app: scouter
service: scouter

frameworkVersion: "2"

provider:
  name: aws
  stage: dev
  region: us-east-2
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  endpointType: REGIONAL
  ecr:
    images:
      scouterLambdas:
        path: ./
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:us-east-2:*:*"

functions:
  PostGetOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Posts/GetOne/PostGetOne.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Post
          method: get
  PostAddOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Posts/AddOne/PostAddOne.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Post
          method: post
  PostUpdateOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Posts/UpdateOne/PostUpdateOne.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Post
          method: put
  PostDeleteOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Posts/Delete/PostDeleteOne.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Post
          method: delete
  PostGetAllFollowed:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Posts/GetAllFollowed/PostGetAllFollowed.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Post/follow
          method: get
  PostGetAllPage:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Posts/GetAllPage/PostGetAllPage.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Post/Page
          method: get
