org: joabsmith
app: scouter
service: scouter

frameworkVersion: "2"

provider:
  name: aws
  stage: dev
  region: us-east-2
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  endpointType: REGIONAL
  ecr:
    images:
      scouterLambdas:
        path: ./
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:us-east-2:*:*"

functions:
  #Post Lambdas
  PostGetOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Posts/GetOne/PostGetOne.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Post/{postID}/{parentID}
          method: get
          cors: true
          request:
            paramaters:
              paths:
                postID: true
                parentID: true

  PostAddOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Posts/AddOne/PostAddOne.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Post
          method: post
          cors: true
  PostUpdateOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Posts/UpdateOne/PostUpdateOne.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Post
          method: put
          cors: true
  PostDeleteOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Posts/Delete/PostDeleteOne.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Post
          method: delete
          cors: true
  PostGetAllFollowed:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Posts/GetAllFollowed/PostGetAllFollowed.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Post/follow/
          method: post
          cors: true

  PostGetAllPage:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Posts/GetAllPage/PostGetAllPage.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Post/Page/{pageID}
          method: get
          cors: true
          request:
            paramaters:
              paths:
                pageID: true

  #Anime Lambdas
  AnimeGetOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Anime/GetOne/AnimeGetOne.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Anime/{parentID}
          method: get
          cors: true
          request:
            paramaters:
              paths:
                parentID: true
  AnimeAddOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Anime/AddOne/AnimeAddOne.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Anime
          method: post
          cors: true
  AnimeUpdateOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Anime/UpdateOne/AnimeUpdateOne.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Anime
          method: put
          cors: true
  AnimeDeleteOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Anime/DeleteOne/AnimeDeleteOne.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Anime/{parentID}
          method: delete
          cors: true
          request:
            paramaters:
              paths:
                parentID: true
  AnimeGetBySearch:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Anime/GetBySearch/AnimeGetBySearch.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Anime/search/{searchValue}
          method: get
          cors: true
          request:
            paramaters:
              paths:
                searchValue: true
  AnimeGetAll:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/Anime/UpdateOne/AnimeUpdate.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: Anime/all
          method: get
          cors: true
  #User Lambdas
  UserGetOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/User/GetOne/GetUser.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: User/{userID}
          method: get
          cors: true
          request:
            paramaters:
              paths:
                userID: true
  UserAddOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/User/AddOne/AddUser.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: User
          method: post
          cors: true
  UserUpdateOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/User/UpdateOne/UpdateUser.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: User
          method: put
          cors: true
  UserDeleteOne:
    image:
      name: scouterLambdas
      command:
        - "./Lamdas/User/DeleteOne/DeleteUser.handler"
      entryPoint:
        - "/lambda-entrypoint.sh"
    events:
      - http:
          path: User/{userID}
          method: delete
          cors: true
          request:
            paramaters:
              paths:
                userID: true
